name: Run code-server

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [main]

jobs:
  run-code-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install code-server
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh

      - name: Start code-server
        env:
          PASSWORD: ${{ secrets.CODE_SERVER_PASSWORD }}
        run: |
          nohup code-server --auth password --bind-addr 0.0.0.0:8080 &

      - name: Expose code-server with ngrok (optional)
        env:
          NGROK_AUTH_TOKEN: 34X9kAeqnxi5nMPmlH5i4oat2vK_74JyC3mV756via2yQHCSB
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y
          ngrok config add-authtoken $NGROK_AUTH_TOKEN
          nohup ngrok http 8080 &

      - name: Wait and show URL
        run: |
          sleep 5
          echo "Visit your code-server via ngrok dashboard or logs:"
          curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
